### PR TITLE
Remove rounding from the "full" bool in the `Ship refuelled` event.

### LINKED ISSUE #1410: Ship refuelled event - event.full always true
## EDDI version in which issue is found
V3.4.1 and v3.4.2-b1, with the default EDDI personality.

## VoiceAttack version in which issue is found (as applicable)
V1.7.7

## Steps to reproduce
Scoop fuel at a star.

## Expected
Ship refuelled event only makes one report.

## Observed
About half the time, the event will report twice from scooping fuel.

## Investigation
After hearing some reports twice for a single scoop action, I looked into what was going on.  The Journal is reporting fuel twice, as we have noted in the past and subsequently accounted for in the script, but it looked like that wasn't working anymore.
```
{ "timestamp":"2019-07-20T22:45:28Z", "event":"FuelScoop", "Scooped":5.002489, "Total":31.581266 }
{ "timestamp":"2019-07-20T22:45:28Z", "event":"FuelScoop", "Scooped":0.418732, "Total":32.000000 }
```

Well, after messing about with variables to try to fix it, I ended up making the script just list the state of all variables, and this is when I found that 'event.full' is always set to true, even when the scoop was only the first report of 5.002489, which is what we accounted for in the script.  Thus the script is always executing the '{if event.full:' part of the code, even if the scoop wasn't a full completion.

> 13. Fuel remaining: 31.581266. Event total: 31.581266. Event full: true. A. Maximum fuel
> 14. Fuel remaining: 32. Event total: 32. Event full: true. A. Fuel at maximum

I named the {if event.full: as A. and the |else: as B.  The 13 & 14 are an incremental count of the number of executions of the event as I was testing.

As you can see from number 13, event.full should not be set as true.  This was immediately after an EDDI and game load, so the variable is set as true right from the start and not just getting stuck after a full refuel.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1410.

### CODE REVIEW

File: JournalMonitor/JournalMonitor.cs [hunk 1]
```diff
@@ -2594,7 +2594,7 @@ async void ModuleArrived()
                                     decimal total = JsonParsing.getDecimal(data, "Total");
                                     bool full = EDDI.Instance.CurrentShip?.fueltanktotalcapacity == null
                                         ? false
-                                        : Math.Round(total) == EDDI.Instance.CurrentShip.fueltanktotalcapacity;
+                                        : total == (EDDI.Instance.CurrentShip.fueltanktotalcapacity ?? 0M);
```
Comment (richardbuckle) [inline JournalMonitor/JournalMonitor.cs]: Floating point `==` is vulnerable to underflow errors. I recommend instead:
`Math.Abs(total - (EDDI.Instance.CurrentShip.fueltanktotalcapacity ?? 0M)) <= 0.000001M`

File: JournalMonitor/JournalMonitor.cs [hunk 2]
```diff
@@ -2594,7 +2594,7 @@ async void ModuleArrived()
                                     decimal total = JsonParsing.getDecimal(data, "Total");
                                     bool full = EDDI.Instance.CurrentShip?.fueltanktotalcapacity == null
```
Comment (richardbuckle) [inline JournalMonitor/JournalMonitor.cs]: Let's introduce a variable for `EDDI.Instance.CurrentShip` to improve readability.

File: JournalMonitor/JournalMonitor.cs (hunk 1 above)
Comment (richardbuckle) [reply JournalMonitor/JournalMonitor.cs]: On investigation, `decimal` is designed to be safe for such comparisons, unlike `float` and `double` so I can let it slide if you like.
