### PR TITLE
Remember voice settings in our synth and only set them again if they need to change.

### LINKED ISSUE #891: Cereproc Heather's voice inconsistently throws exception
## EDDI version in which issue found
EDDI 3.1.0-b3 running as VoiceAttack plugin
Cannot reproduce in 3.0.3

## Steps to reproduce

1. Select Cereproc Heather as the TTS voice in EDDI
2. Ensure all voice traffic goes thru EDDI as a plugin call

## Expected
Heather's voice to be played

## Observed
Sometimes Heather plays fine, sometimes Windows falls back to another voice.

## Investigation
Attached debugging log and observed exceptions.  It does not appear to make a difference whether the voice is initiated from a call from Voice Attack with an EDDI 'say' command, or if it's just the built-in speech responder pushing the text.  No idea why an exception is only sometimes thrown.
[eddi1.zip](https://github.com/EDCD/EDDI/files/2522444/eddi1.zip)

I just tried standalone, and still reproduced the issue.  I have both 32 and 64 bit versions of Heather installed.
[eddi-standalone.log](https://github.com/EDCD/EDDI/files/2522467/eddi-standalone.log)

### PR DESCRIPTION
**Pull request by Tkael**
Fix #891.

### CODE REVIEW

File: SpeechService/SpeechService.cs [hunk 1]
```diff
@@ -446,11 +446,15 @@ private void speak(MemoryStream stream, string voice, string speech)
...
         private static void selectVoice(string voice)
         {
+            if (synth.Voice.Name == voice)
+            {
+                return;
+            }
             foreach (InstalledVoice vc in synth.GetInstalledVoices())
             {
-                if (vc.Enabled && vc.VoiceInfo.Name == voice && !vc.VoiceInfo.Name.Contains("Microsoft Server Speech Text to Speech Voice"))
+                if (vc.VoiceInfo.Name == voice && !vc.VoiceInfo.Name.Contains("Microsoft Server Speech Text to Speech Voice"))
```
Comment (richardbuckle) [inline SpeechService/SpeechService.cs]: At first sight these are logically identical but never mind.
