### PR TITLE
Fix local commodity definitions affecting data passed to EDDN

### LINKED ISSUE #1906: Local commodity definitions can change the edName reported by the EDDN responder on the `commodity` schema
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Observe the output of an EDDN message for commodity ID 128667076

## Expected
The commodity name should be "SanumaMEAT"

## Observed
The commodity name is "SanumaDecorativeMeat"

## Investigation
- We pass CommodityMarketQuote objects inside of the MarketInformationUpdated event to the EDDN responder. The EDDN responder passes the edName property from the commodity definition property of the object as the commodity name.
- CommodityMarketQuote  objects are generated by looking up the local commodity definition by commodity ID. The edName in the commodity definition originates from EDDI's internal definition rather than from the original name given in the cAPI response or from market.json.
- This is a severe problem because the commodity id is not passed via the EDDN schema. The commodity edName is the primary key for all EDDN feed consumers and it is being transformed / not being conserved when we look up and apply a local definition by its commodity ID.

Proposed solution: We handle station updates in the same methods where we generate the MarketInformationUpdated events, and consequently we can pass the original values to the EDDN responder in the MarketInformationUpdated event rather than values which may have been transformed by EDDI's internal definitions. 
- For the commodities endpoint, pass List\<EDCommodityMarketQuote\>, where each EDCommodityMarketQuote contains only the original data received from cAPI or from market.json and is similar to the current `EDDNCommodity` class currently in the EDDNResponder namespace)
- For the outfitting endpoint, pass List\<string\>, where each string is an edName for a module.
- For the shipyard endpoint, pass List\<string\>, where each string is an edName for a ship model.

### LINKED ISSUE #1931: Partial update of carrier commodities on EDDN
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. List items for purchase on carrier. In my case, I placed 6. (Alexandrite, Bromellite, Grandidierite, LTD, Painite, Void Opal)
2. Launch from carrier and dock.
3. Enter commodities
4. Check EDDN/EDDB for carrier commodity listings after some time.

## Expected
Expected all items to be updated on EDDN.

## Observed
Only 3 items updated. 
image
image

## Investigation
EDMC does not have this issue. I am able to see all my carrier listings on EDDN/EDDB after updating.

### LINKED ISSUE #1953: `Market information updated` event script does not perform purchase, sales, or swapout checks
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
(as reported by https://forums.frontier.co.uk/threads/eddi-scripts-and-eddi-enabled-va-commands-thread.311614/post-8674717)
1. Dock at a station where the `Market information updated` event would normally trigger a Commodity sale check, commodity purchase check, or swapout check.
2. Note that no such checks occur.

## Expected
Perform purchase, sales, or swapout checks as appropriate

## Observed
No such checks occur, as they all depend on the value of the removed property `event.update`.

## Investigation
1. Review the `Market information script`
2. Note that it expects and depends on an undocumented property `event.update`
3. Review MarketInformationUpdatedEvent.cs
4. Note that the `update` property was removed in commit https://github.com/EDCD/EDDI/commit/0647191ab55a0eb0fcfc9dad0bcd89fad4e5ad35 (Aug. 2019) (oops!)

### PR DESCRIPTION
**Pull request by Tkael**
Resolves #1906, resolves #1931, & resolves #1953.
- Moves parsing CAPI `profile` results from `CompanionAppService.cs` into `CompanionAppProfileFromJson.cs` (to separate authentication from parsing the results)
- Sorts commodities by EliteId and updates commodity definitions to provide a short term resolution for #1906.
  - SanumaMEAT was SanumaDecorativeMeat
  - Wolf1301Fesh was WolfFesh
  - CD75CatCoffee was CD-75KittenBrandCoffee
  - AerialEdenApple was EdenApplesOfAerial
  - UzumokuLowGWings was UzumokuLow-GWings
- Passes only original data to the EDDN responder.
- Updates profile.cs to also only pass original data
- Removes the EDID property from the `FrontierApiCommander.cs` class (the ID returned from the Frontier API was found to not match the FID returned from the player journal)
- Implements an optional enum for commodity stock and demand brackets, standardizing the data type for brackets (which were either `dynamic` or `int` for the `CommodityMarketQuote` or `MarketInfo` classes respectively)
- Uses a common `MarketInfoItem` class to capture commodity market quote information from the Frontier API or from market.json, ready to pass to the EDDN responder, and uses the `CommodityMarketQuote` class when we are ready to embed an EDDI data definition.
- Exposes imports, exports, and prohibited commodities as localized commodity objects and updates documentation accordingly. Updates the `Cargo report` script (to use commodity objects for the station `prohibited` list)
- Revised the `Market information updated` script to resolve #1953.

### CODE REVIEW

File: CompanionAppService/CompanionAppProfileFromJson.cs [hunk 1]
```diff
@@ -0,0 +1,297 @@
...
+using Utilities;
+
+namespace EddiCompanionAppService
+{
+    public partial class CompanionAppService
+    {
+        /// <summary>Create a  profile given the results from a /profile call</summary>
+        public static Profile ProfileFromJson(string data, DateTime timestamp)
+        {
+            Profile profile = null;
```
Comment (GioVAX) [inline CompanionAppService/CompanionAppProfileFromJson.cs]: This temp variable is not necessary and could be removed, resulting in simpler code.

File: CompanionAppService/CompanionAppProfileFromJson.cs [hunk 2]
```diff
@@ -0,0 +1,297 @@
...
+        /// <summary>Create a profile given the results from a /profile call</summary>
+        public static Profile ProfileFromJson(JObject json, DateTime timestamp)
+        {
+            Profile Profile = new Profile
+            {
+                json = json,
+                timestamp = timestamp
+            };
+
+            if (json["commander"] != null)
```
Comment (GioVAX) [inline CompanionAppService/CompanionAppProfileFromJson.cs:33]: I know we want to change the way we parse JSON in the future, but this is an opportunity to try a new approach and see how it works.
Also, it will reduce the number of changes we'll need to do once we decide to migrate ;)

File: CompanionAppService/CompanionAppProfileFromJson.cs [hunk 3]
```diff
@@ -0,0 +1,297 @@
...
+                    }
+                }
+            }
+            return edModules;
+        }
+
+        // Obtain the list of station economies from the profile
+        public static List<ProfileEconomyShare> EconomiesFromProfile(dynamic json)
+        {
+            List<ProfileEconomyShare> Economies = new List<ProfileEconomyShare>();
```
Comment (GioVAX) [inline CompanionAppService/CompanionAppProfileFromJson.cs]: Should this be `economies`?
Also, in other parts of the code in the declaration, we use `var`.

File: CompanionAppService/CompanionAppProfileFromJson.cs [hunk 4]
```diff
@@ -0,0 +1,297 @@
...
+        // Obtain the list of ships available at the station from the profile
+        public static List<ProfileShip> ShipyardFromProfile(JObject json)
+        {
+            List<ProfileShip> edShipyardShips = new List<ProfileShip>();
+
+            if (json["lastStarport"] != null && json["lastStarport"]["ships"] != null)
+            {
+                // shipyard_list is a JObject containing JObjects but let's code defensively because FDev
+                var shipyardList = json["lastStarport"]["ships"]["shipyard_list"].Children();
+                foreach (JToken shipToken in shipyardList.Values())
```
Comment (GioVAX) [inline CompanionAppService/CompanionAppProfileFromJson.cs]: Any reason not to use LINQ?

```
var edShipyardShips = shipyardList.Values()
    .Select( v => ShipyardShipFromProfile( v as JObject );
```

File: DataDefinitions/CommodityDefinition.cs [hunk 5]
```diff
@@ -519,6 +525,38 @@ private static bool ignoredCommodity(string name)
             }
         }
 
+        private static bool obsoleteCommodityEdName(string name, out string correctedName)
```
Comment (GioVAX) [inline DataDefinitions/CommodityDefinition.cs]: We could remove the bool, and just return the normalized commodity name (changed if necessary, or as is otherwise).
Who cares if the name was actually changed?

File: DataDefinitions/EddnCommodityMarketQuote.cs [hunk 6]
```diff
@@ -0,0 +1,135 @@
...
+            meanPrice = (int)capiJSON["meanPrice"];
+            stock = (int)capiJSON["stock"];
+            buyPrice = (int)capiJSON["buyPrice"];
+            stockBracket = capiJSON["stockBracket"]?.ToObject<CommodityBracket?>();
+            sellPrice = (int)capiJSON["sellPrice"];
+            demand = (int)capiJSON["demand"];
+            demandBracket = capiJSON["demandBracket"]?.ToObject<CommodityBracket?>();
+            if (capiJSON["statusFlags"] != null)
+            {
+                foreach (string statusFlag in capiJSON["statusFlags"])
```
Comment (GioVAX) [inline DataDefinitions/EddnCommodityMarketQuote.cs]: If capiJSON["statusFlags"] is a `Enumerable`, this could become
`statusFlags = capiJSON["statusFlags"].Cast<string>();`

File: DataDefinitions/MarketInfo.cs [hunk 7]
```diff
@@ -23,13 +23,13 @@ public class MarketInfo
         [JsonProperty]
         public int stock { get; set; }
         [JsonProperty]
-        public int stockbracket { get; set; }
+        public CommodityBracket? stockbracket { get; set; }
```
Comment (GioVAX) [inline DataDefinitions/MarketInfo.cs]: Just curious: why optional?
Previously `int` was not optional.

File: EDDI/EDDI.cs [hunk 8]
```diff
@@ -1572,42 +1572,50 @@ private bool eventLiftoff(LiftoffEvent theEvent)
 
         private bool eventMarket(MarketEvent theEvent)
         {
-            if (allowMarketUpdate)
+            // Don't proceed if we've already viewed the market while docked or when loading pre-existing logs
+            if (allowMarketUpdate && !theEvent.fromLoad)
```
Comment (GioVAX) [inline EDDI/EDDI.cs]: To simplify a bit, we could turn this `if` and return immediately.
E.g.
```
if( theEvent.fromLoad || ! allowMarketUpdate )
    return false;
....
```

File: EDDI/EDDI.cs [hunk 9]
```diff
@@ -1616,14 +1624,19 @@ private bool eventMarket(MarketEvent theEvent)
 
         private bool eventOutfitting(OutfittingEvent theEvent)
         {
-            if (allowOutfittingUpdate)
+            // Don't proceed if we've already viewed outfitting while docked or when loading pre-existing logs
+            if (allowOutfittingUpdate && !theEvent.fromLoad)
```
Comment (GioVAX) [inline EDDI/EDDI.cs]: Same as above.

File: EDDI/EDDI.cs [hunk 10]
```diff
@@ -1616,14 +1624,19 @@ private bool eventMarket(MarketEvent theEvent)
...
                     && info.StarSystem == theEvent.system
                     && info.StationName == theEvent.station
                     && info.Horizons == Instance.inHorizons)
                 {
+                    // Post an update event for new outfitting data
+                    enqueueEvent(new MarketInformationUpdatedEvent(info.timestamp, theEvent.system, theEvent.station, theEvent.marketId, null, null, info.Items.Select(i => i.name).ToList(), null, inHorizons));
+
+                    // Update the current station outfitting
                     List<EddiDataDefinitions.Module> modules = new List<EddiDataDefinitions.Module>();
                     foreach (OutfittingInfo item in info.Items)
```
Comment (GioVAX) [inline EDDI/EDDI.cs]: This block could be simplified with LINQ.
```
var modules = info.Items
    .Select( i => EddiDataDefinitions.Module.FromOutfittingInfo(i))
    .Where( i => i ! null )
    .ToList();
```

File: EDDI/EDDI.cs [hunk 11]
```diff
@@ -1661,7 +1667,8 @@ private bool eventOutfitting(OutfittingEvent theEvent)
 
         private bool eventShipyard(ShipyardEvent theEvent)
         {
-            if (allowShipyardUpdate)
+            // Don't proceed if we've already viewed outfitting while docked or when loading pre-existing logs
+            if (allowShipyardUpdate && !theEvent.fromLoad)
```
Comment (GioVAX) [inline EDDI/EDDI.cs]: As previous `if`s

File: EDDI/EDDI.cs [hunk 12]
```diff
@@ -1678,12 +1685,14 @@ private bool eventShipyard(ShipyardEvent theEvent)
                             ships.Add(ship);
```
Comment (GioVAX) [inline EDDI/EDDI.cs]: This block could be simplified as above.

**Review by GioVAX — CHANGES_REQUESTED** [review]

File: CompanionAppService/CompanionAppProfileFromJson.cs (hunk 2 above)
Comment (Tkael) [reply CompanionAppService/CompanionAppProfileFromJson.cs:33]: Changing the overall parsing strategy adds additional risk to this PR. I don't think that it makes sense for us to do that right now.

File: CompanionAppService/CompanionAppProfileFromJson.cs (hunk 1 above)
Comment (Tkael) [reply CompanionAppService/CompanionAppProfileFromJson.cs]: Agreed. Update pushed.

File: DataDefinitions/EddnCommodityMarketQuote.cs (hunk 6 above)
Comment (Tkael) [reply DataDefinitions/EddnCommodityMarketQuote.cs:65]: As far as I'm aware, statusFlags is not an Enumberable.

File: DataDefinitions/MarketInfo.cs (hunk 7 above)
Comment (Tkael) [reply DataDefinitions/MarketInfo.cs]: We've seen from the Frontier API that the enum can be null. Making it optional allows for that possibility in Market.json

File: CompanionAppService/CompanionAppProfileFromJson.cs (hunk 3 above)
Comment (Tkael) [reply CompanionAppService/CompanionAppProfileFromJson.cs]: I'll revise to `economyShares`.

File: DataDefinitions/CommodityDefinition.cs (hunk 5 above)
Comment (Tkael) [reply DataDefinitions/CommodityDefinition.cs]: Ok

File: EDDI/EDDI.cs (hunk 10 above)
Comment (Tkael) [reply EDDI/EDDI.cs]: ok

File: CompanionAppService/CompanionAppProfileFromJson.cs (hunk 2 above)
Comment (Tkael) [reply CompanionAppService/CompanionAppProfileFromJson.cs:33]: Additionally, you aren't being very clear about the method that you think we should be adopting here. ;-)

File: EDDI/EDDI.cs (hunk 12 above)
Comment (Tkael) [reply EDDI/EDDI.cs]: ok

File: EDDI/EDDI.cs (hunk 8 above)
Comment (Tkael) [reply EDDI/EDDI.cs]: ok

File: EDDI/EDDI.cs (hunk 9 above)
Comment (Tkael) [reply EDDI/EDDI.cs]: ok

File: EDDI/EDDI.cs (hunk 11 above)
Comment (Tkael) [reply EDDI/EDDI.cs]: ok

File: CompanionAppService/CompanionAppProfileFromJson.cs (hunk 4 above)
Comment (Tkael) [reply CompanionAppService/CompanionAppProfileFromJson.cs]: Looks like `CapiShipyardTests` validates changes to how we parse this so this is a low risk change. Ok.

File: DataDefinitions/EddnCommodityMarketQuote.cs (hunk 6 above)
Comment (Tkael) [reply DataDefinitions/EddnCommodityMarketQuote.cs]: I'm getting an invalid cast exception with the proposed code.
Note: `statusFlags` is a list so I appended `.ToList()`

File: CompanionAppService/CompanionAppProfileFromJson.cs (hunk 2 above)
Comment (GioVAX) [reply CompanionAppService/CompanionAppProfileFromJson.cs:33]: That's true 😆 
I was thinking to Newtonsoft `JsonConvert.DeserializeObject<T>(json)`

File: DataDefinitions/EddnCommodityMarketQuote.cs (hunk 6 above)
Comment (GioVAX) [reply DataDefinitions/EddnCommodityMarketQuote.cs]: Ok.

File: DataDefinitions/MarketInfo.cs (hunk 7 above)
Comment (GioVAX) [reply DataDefinitions/MarketInfo.cs]: Thanks for the explanation 😃

**Review by GioVAX — APPROVED** [review]

**Comment by Tkael** [comment]
Updated to resolve #1931, improve testing, and consolidate some similar classes.
