### PR TITLE
Standardize and fix timestamp parsing

### LINKED ISSUE #1571: Munged timestamps in EDDN commodity/shipyard/outfitting messages
https://github.com/EDCD/EDDI/blob/493b03e74f23e4aa46918f4cd4692815fd2b54bb/EDDI/MarketInfoReader.cs#L12

Without `System.Globalization.DateTimeStyles.AdjustToUniversal`, this converts the timestamp to local time.  This is resulting in about 30% of EDDI's Commodity messages (and likely Shipyard and Outfitting messages as well) having munged timestamps.

### PR DESCRIPTION
**Pull request by Tkael**
Resolves #1571
Replaces #1572 

- Centralizes DateTime parsing to a new `getDateTime` method in Utilities.cs
- Centralizes conversion from DateTime to epoch seconds to the already existing `fromDateTimeToSeconds` method in Utilities.cs.
- Simplifies MarketInfoReader.cs, OutfittingInfoReader.cs, and ShipyardInfoReader.cs to deserialize directly to the DateTime rather than deserializing to a string and then converting to a DateTime.

### CODE REVIEW

File: Utilities/JsonParsing.cs [hunk 1]
```diff
@@ -42,17 +46,17 @@ public static DateTime getDateTime(string key, object val)
...
             {
-                if (DateTime.TryParseExact(str, "o", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var result))
+                if (DateTime.TryParseExact(str, "yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal, out var result))
                 {
                     // Journal format ("2019-09-24T02:40:34Z")
-                    return result.ToUniversalTime();
+                    return result;
                 }
-                if (DateTime.TryParseExact(str, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out result))
+                if (DateTime.TryParseExact(str, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal, out result))
```
Comment (klightspeed) [inline Utilities/JsonParsing.cs]: Since EDSM time is already UTC, but has no timezone specified, then you will need `DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal` here.
