### PR TITLE
Fix exceptions related to starting in an SRV

### LINKED ISSUE #1894: Exception has been thrown by the target of an invocation (when starting in an SRV)
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
1. It seems after using a SRV and then boarding the ship , EDDI is getting confused. 
2. If you make a Supercruise jump, EDDI will report "your SRV is in transit to..." which is what has lead me to believe it is when this problem starts.
3. This also affects other scripts like the script run after fuel scooping, the discovery script, the star discovery script, etc after this and the only way to resolve this that I have found is to reboot my PC. 
3.1 Scripts start reporting "Exception has been thrown by the target of an invocation"
3.2 (Full Log Line) 2020-07-13T17:02:14 [Info] EDDI:eventJumped Jumped to Har Itari 
2020-07-13T17:02:14 [Warning] ScriptResolver:resolveFromValue Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
3.3 

## Expected
Scripts to run as they normally would and report on event.

## Observed
This started happening when I upgraded to version 3.7.0. 
[EDDI.zip](https://github.com/EDCD/EDDI/files/4914092/EDDI.zip)

This seems to happen after using a SRV on a planet surface and then boarding the ship again. 

## Investigation
I was using a modified personality so I changed back to the default personality with no successes. 

I attached a ZIP of the logs.

### LINKED ISSUE #1899: Wrong ship details when starting in SRV
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.6

## Steps to reproduce
1. Start Elite Dangerous Horizon in a SRV. Voice attack profile includes ((EDDI: ship variables)) from EDDI.vap(supplied with EDDI). created a ((EDDI commander loading)) voice attack entry that calls the ((EDDI: ship variables)).

## Observed
The above reports the ship is a Diamondback Explorer, which I do not have currently in my fleet on the account (never have had one). se below attached output from Voiceattack
[Landed out put at Commander Loaded for SRV.txt](https://github.com/EDCD/EDDI/files/4941971/Landed.out.put.at.Commander.Loaded.for.SRV.txt)

## Investigation
No further Investigation done. When in ship all reported correctly, currently do not have a SLF to test with that.

### LINKED ISSUE #1907: Almost every script is erroring
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.7.0

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
VoiceAttack was not running/installed

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
Don't know why it's happening

## Expected
[Describe what you expected to happen]
I expected the voice to work not to repeatedly say "an exception has been thrown by the target of an invocation" over and over

## Observed
[Describe what happened instead]
says fuel level is at 0%, fuel limit script failed, star system script failed, and several other scripts have failed with the same error.

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
Uninstalled 3.7.0, deleted %APPDATA%\EDDI and reinstalled 3.7.0 and still happening (this log is from the reinstall). Installed 3.5.3.b7 and working as expected without any exception errors.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1894, fixes #1899, and fixes #1907. 

1. The ship model is being passed from the `Commander continued` event as "SRV" rather than as "TestBuggy" (the FDev internal name for the SRV).
2. Starting the game in an SRV isn't supposed to create a new entry in the ship monitor and change your currently active ship, but because the ship model is set to "SRV" (rather than "TestBuggy", which is what the Ship monitor currently expects), our internal filter on creating a new ship and setting it as the active ship fails in this circumstance.
3. That leaves us with an unintended SRV "ship" with various null / undefined values. 
4. In particular, this creates a null reference exception when trying to access the "Size" property of the SRV "ship" (since the size is determined by the ship model and there is no ship model matching "SRV")

### CODE REVIEW

File: DataDefinitions/Ship.cs [hunk 1]
```diff
@@ -33,11 +33,11 @@ public class Ship : INotifyPropertyChanged
 
         /// <summary>the size of this ship</summary>
         [JsonIgnore]
-        public LandingPadSize Size { get; set; }
+        public LandingPadSize Size { get; set; } = LandingPadSize.Small;
 
         /// <summary>the spoken size of this ship</summary>
         [JsonIgnore]
-        public string size => Size.localizedName;
+        public string size => (Size ?? LandingPadSize.Small).localizedName;
```
Comment (GioVAX) [inline DataDefinitions/Ship.cs:40]: Given the change above, checking for null here is redundant,

File: Tests/ShipTests.cs [hunk 2]
```diff
@@ -579,5 +579,30 @@ public void TestShipJumpedEvent()
...
+            // Set up our `Ship monitor` private object
+            ShipMonitor shipMonitor = new ShipMonitor();
+            PrivateObject privateObject = new PrivateObject(shipMonitor);
+            privateObject.SetFieldOrProperty("updatedAt", DateTime.MinValue);
+
+            // Set up our `currentShipId` property with a value of "9999"
+            privateObject.SetFieldOrProperty("currentShipId", 9999);
+
+            // Set up our event (which reports that we are in an SRV with a ship id of "9998")
+            string line = @"{ ""timestamp"":""2020-07-20T15:40:45Z"", ""event"":""LoadGame"", ""FID"":""F0000000"", ""Commander"":""TestCommander"", ""Horizons"":true, ""Ship"":""TestBuggy"", ""Ship_Localised"":""SRV Scarab"", ""ShipID"":9998, ""ShipName"":"""", ""ShipIdent"":"""", ""FuelLevel"":0.000000, ""FuelCapacity"":0.000000, ""GameMode"":""Group"", ""Group"":""Children of Raxxla"", ""Credits"":5065687467, ""Loan"":0 }";
```
Comment (GioVAX) [inline Tests/ShipTests.cs:595]: IIUC, this test was added to check that the code recognizes the string `SRV`.
Should we also have a test to check for `TestBuggy`?

**Review by GioVAX — CHANGES_REQUESTED** [review]

File: Tests/ShipTests.cs (hunk 2 above)
Comment (Tkael) [reply Tests/ShipTests.cs:595]: It actually is constructed using "TestBuggy" as the ship (matching what we see in-game). The name isn't transformed from "TestBuggy" to "SRV"  until the .ctor for the `Commander continued` event.

The solution is designed to work equally well whether "TestBuggy" or "SRV" is passed from the `Commander continued` event.

File: DataDefinitions/Ship.cs (hunk 1 above)
Comment (Tkael) [reply DataDefinitions/Ship.cs:40]: A little bit, yes. I'd prefer to error on the side of safety / redundancy a bit with the null protection though.

File: Tests/ShipTests.cs (hunk 2 above)
Comment (GioVAX) [reply Tests/ShipTests.cs:595]: I see.
Is there any way that we can test both cases?
Which was my original point but I worded it soo poorly that it got lost... :-D

Comment (Tkael) [reply Tests/ShipTests.cs:595]: Test updated.

**Review by GioVAX — APPROVED** [review]
