### PR TITLE
Fix `Distance()` function returning incorrect results.

### LINKED ISSUE #1884: Distance() function giving wrong results
## EDDI version in which issue is found
v3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Use the Distance() function to find the distance between two star systems.  For example {Distance("Colonia", "Hephaestus")}

## Expected
The correct distance to be given. For Example "11.55"

## Observed
The distance reported is very wrong. For example "19829.03"

## Investigation
I was having trouble with my route plotting, as I wanted to see if I could just discard the whole thing in favour of the EDDI default.  I tracked down my problem to the Distance() function which was producing wildly wrong distances.

As above, for Colonia to Hephaestus (which is only 11.55 LY) it is reporting 19829.03 LY. I've also tried with Sol to Alpha Centauri (which is 4.38 LY) and that reported only 3.03 LY.

I reverted back to EDDI v3.5.2 and Distance() works perfectly fine, giving the correct distances.  I reinstalled v3.7.0 and they are once again very wrong.

I had been initially using the X Y Z co-ords for Distance() when I found it to be wrong, so I tried just the system names directly, but it's still doing the same.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1884.

```cs
(curr.y ?? 0 - dest.y ?? 0)
```
is being interpreted like
```cs
(curr.y ?? (0 - dest.y) ?? 0)
```
when
```cs
((curr.y ?? 0) - (dest.y ?? 0))
```
was intended.

### CODE REVIEW

File: SpeechResponder/ScriptResolver.cs [hunk 1]
```diff
@@ -1186,9 +1186,13 @@ CommodityMarketQuote CommodityDetails(string commodityLocalizedName, Station sta
 
                 if (curr?.x != null && dest?.x != null)
                 {
-                    result = (decimal)Math.Round(Math.Sqrt(square((double)(curr.x - dest.x))
-                                + square((double)(curr.y ?? 0 - dest.y ?? 0))
-                                + square((double)(curr.z ?? 0 - dest.z ?? 0))), 2);
+                    result = (decimal)Math.Round(
+                        Math.Sqrt(
+                                square((double)(curr.x - dest.x)) +
+                                square((double)((curr.y ?? 0) - (dest.y ?? 0))) +
```
Comment (richardbuckle) [inline SpeechResponder/ScriptResolver.cs]: I don't like the defaulting to 0 here. These are [null-lifted operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#lifted-operators) and will propogate null if either side is null.

File: SpeechResponder/ScriptResolver.cs [hunk 2]
```diff
@@ -1186,9 +1186,13 @@ CommodityMarketQuote CommodityDetails(string commodityLocalizedName, Station sta
 
                 if (curr?.x != null && dest?.x != null)
                 {
-                    result = (decimal)Math.Round(Math.Sqrt(square((double)(curr.x - dest.x))
-                                + square((double)(curr.y ?? 0 - dest.y ?? 0))
-                                + square((double)(curr.z ?? 0 - dest.z ?? 0))), 2);
+                    result = (decimal)Math.Round(
+                        Math.Sqrt(
```
Comment (richardbuckle) [inline SpeechResponder/ScriptResolver.cs]: I would hoist this to a local variable, perhaps called `distance`. 
Zero cost and increases readability.

**Review by richardbuckle — COMMENTED** [review]
There are no unit tests.

**Comment by richardbuckle** [comment]
It isn't clear to me from the diff where the error was. Please can we write that up?

**Review by richardbuckle — CHANGES_REQUESTED** [review]
Given the lack of tests, it's not immediately clear to me how the fix works.

File: SpeechResponder/ScriptResolver.cs (hunk 1 above)
Comment (Tkael) [reply SpeechResponder/ScriptResolver.cs]: > It isn't clear to me from the diff where the error was. Please can we write that up?

I believe 
```cs
(curr.y ?? 0 - dest.y ?? 0)
```
is being interpreted like
```cs
(curr.y ?? (0 - dest.y) ?? 0)
```
when
```cs
((curr.y ?? 0) - (dest.y ?? 0))
```
was intended.

**Comment by Tkael** [comment]
Ok, I've added several unit tests and improved code legibility. I also found a couple of other places where we were running very similar code and consolidated distance calculations so that they'll all use the same methods.

File: SpeechResponder/ScriptResolver.cs (hunk 2 above)
Comment (Tkael) [reply SpeechResponder/ScriptResolver.cs]: Done.

File: DataDefinitions/Ship.cs [hunk 3]
```diff
@@ -448,15 +448,12 @@ public string SpokenModel()
         public decimal? Distance(decimal? fromX, decimal? fromY, decimal? fromZ)
         {
             // Work out the distance to the system where the ship is stored if we can
-            if (x is null || y is null || z is null || fromX is null || fromY is null || fromZ is null)
-            {
-                // We don't know how far away the ship is
-                return null;
+            if (x != null && y != null && z != null && fromX != null && fromY != null && fromZ != null)
```
Comment (richardbuckle) [inline DataDefinitions/Ship.cs]: Is there merit in pushing the null-checking into `Functions.DistanceFromCoordinates()` itself?

File: DataDefinitions/StarSystem.cs [hunk 4]
```diff
@@ -367,5 +368,16 @@ private long estimateSystemValue(IList<Body> bodies)
 
             return value;
         }
+
+        public decimal? DistanceFromStarSystem(StarSystem other)
+        {
+            // Work out the distance to the other star system if we can 
+            if (x != null && y != null && z != null && other?.x != null && other.y != null && other.z != null)
```
Comment (richardbuckle) [inline DataDefinitions/StarSystem.cs]: As above, is there merit in pushing the null-checking into `Functions.DistanceFromCoordinates()` itself?

**Comment by richardbuckle** [comment]
This looks good but before we merge I'd like your views on my comments just above.

Also, don't forget that C# supports [lifted operators for nullable types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#lifted-operators) which can sometimes be used to make code simpler.

File: DataDefinitions/Ship.cs (hunk 3 above)
Comment (Tkael) [reply DataDefinitions/Ship.cs]: Ok. Update pushed.

File: DataDefinitions/StarSystem.cs (hunk 4 above)
Comment (Tkael) [reply DataDefinitions/StarSystem.cs]: Ok. Update pushed.

**Comment by richardbuckle** [comment]
I relent.

**Review by richardbuckle — APPROVED** [review]
