### PR TITLE
Correct invalid EDDN messages

### LINKED ISSUE #1275: FSDJump events are rejected by EDDN
## EDDI version in which issue is found
3.3.7

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Send an FSDJump event to EDDN and review the contents of the response message. 

## Expected
```
Content "OK"
```

## Observed
```
Content: "FAIL: [<ValidationError: "{u'type': [u'array', u'boolean', u'integer', u'number', u'null', u'object', u'string']} is not allowed for u'Anarchy'">]"
```

## Investigation
Properties ending in "_Localised" are supposed to be stripped prior to sending to EDDN, but they are present in the outbound message contents. EDDN is rejected these as invalid.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1275 
Corrects "_Localised" properties not being stripped correctly (causing "Jumped" messages to be rejected as invalid). 
Strips latitude and longitude.
Improves error reporting for invalid messages submitted to EDDN.

### CODE REVIEW

File: EDDNResponder/EDDNResponder.cs [hunk 1]
```diff
@@ -258,6 +260,7 @@ private bool LocationIsSet()
                     ((IDictionary<string, object>)faction).Remove("SquadronFaction");
                     ((IDictionary<string, object>)faction).Remove("HappiestSystem");
                     ((IDictionary<string, object>)faction).Remove("HomeSystem");
+                    ((IDictionary<string, object>)faction).Where(x => !x.Key.EndsWith("_Localised")).ToDictionary(x => x.Key, x => x.Value);
```
Comment (richardbuckle) [inline EDDNResponder/EDDNResponder.cs]: Aren't we ignoring the return value here?

File: EDDNResponder/EDDNResponder.cs [hunk 2]
```diff
@@ -258,6 +260,7 @@ private bool LocationIsSet()
                     ((IDictionary<string, object>)faction).Remove("SquadronFaction");
```
Comment (richardbuckle) [inline EDDNResponder/EDDNResponder.cs]: I would probably introduce a variable so I only have to do the cast once, for readability. Not a big deal though.

**Comment by Tkael** [comment]
Looks good. Merging.
