### PR TITLE
Fix dispatcher timing for writing shipyard data

### LINKED ISSUE #305: Corrupted shipmonitor.json
## EDDI version in which issue found
2.4.6-b1

## Steps to reproduce

1. Unknown : Files requested by Tkael

## Expected
Fuel tank level reporting to match actual.

## Observed
Always stated that fuel tank was empty or less than 25% in Imperial Cutter

## Investigation
Clearing shipmonitor.json resolved misreporting, sending on file and log as requested.
[shipmonitor.zip](https://github.com/EDCD/EDDI/files/1558073/shipmonitor.zip)
[eddi.log](https://github.com/EDCD/EDDI/files/1558083/eddi.log)

### PR DESCRIPTION
**Pull request by Tkael**
Fix #305 by checking to make sure all dispatcher actions are completed prior to writing to the shipyard.
Though this solution works, there may be a more elegant way to code this (perhaps using Dispatcher.CurrentDispatcher.Hooks.DispatcherInactive)?

### CODE REVIEW

File: ShipMonitor/ShipMonitor.cs [hunk 1]
```diff
@@ -784,8 +786,15 @@ public void HandleProfile(JObject profile)
             return variables;
         }
 
-        public void writeShips()
+        public async void writeShips()
         {
+            do
+            {
+                // Make sure the dispatcher has finished prior to writing the shipyard.
+                await Task.Delay(TimeSpan.FromSeconds(1));
```
Comment (richardbuckle) [inline ShipMonitor/ShipMonitor.cs]: As you say there is probably a more idiomatic way to fix this. Meanwhile this will do as a stopgap.

Right now I only have a web browser to review in, but I wonder if there are other instances of this issue in the codebase. Could you please raise an issue for me to review the codebase for this when I get back?

**Comment by Tkael** [comment]
I'm also away from my dev pc atm, but I've saved the new issue that we can review later.

**Comment by richardbuckle** [comment]
Lots of change here, now that I have fully got fully back up to speed with threading in C# and .NET.

I *think* that the real fix is to write out the shipyard whenever the current ship ID is changed.

That said, I am submitting this as beta for testing.

**Comment by Tkael** [comment]
@richardbuckle These latest changes don't work for me. I purchased a new Sidewinder and heard this:
"Sidewinder purchased. Unidentified ship handover complete."
The sidewinder wasn't entered into my shipyard, and neither renaming the ship, undocking and redocking, nor switching ships created an entry in the shipyard. However, by stepping through the code I know that EDDI is seeing the Sidewinder... it just isn't present at the time the shipyard is written.

**Comment by richardbuckle** [comment]
Thanks for the steps to repro. I had thought that I'd introduced a write every place it was needed but clearly it still isn't synchronised properly. Guess I'll be buying a few Sidewinders when I get back on Friday :-/
