### PR TITLE
Fix high CPU utilization when loading log files and interacting with the ship monitor

### LINKED ISSUE #1238: Shipmonitor.json high cpu usage if it has more than one ship in the file.
## EDDI version in which issue found
3.3.7-B1 Voice Attack only.

## Steps to reproduce

Either log into the Frontier API and switch to Voice Attack or switch to another few ships without being logged into the API.

## Expected

Same CPU usage in the VA plugin as the standalone version.

## Observed
Using Voice Attack Without logging into the API and without switching ships CPU usage is normal(under 2% when not running a command) but as I switch to more ships the CPU usage grows by .5-1% per ship and eventually stops around 40% usage after I have switched to every ship I own(49 total).  It will stay at this level constantly while using Voice Attack.

If I log into the API and then launch Voice Attack it starts using 40% immediately after it picks all of my ships(just the names and that I own them.  It doesn't get the loadouts and stuff until I switch to the ship) from the API but otherwise functions normally without the crashes or slow responses 3.3.5/6 had.
## Investigation
Similar problem to Issue #1182 but it no longer crashes, is slow to respond or climbs in usage constantly.  It just sits at 40% cpu usage constantly.

The standalone works fine with any combination of being logged into the API or any number of ships in the ship monitor.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1238.

### CODE REVIEW

File: DataProviderService/DataProviderService.cs [hunk 1]
```diff
@@ -14,7 +14,7 @@ public class DataProviderService
         // Uses the EDSM data service and legacy EDDP data
         public static StarSystem GetSystemData(string system, bool showCoordinates = true, bool showSystemInformation = true, bool showBodies = true, bool showStations = true, bool showFactions = true)
         {
-            if (system == null) { return null; }
+            if (system == null || string.IsNullOrEmpty(system)) { return null; }
```
Comment (richardbuckle) [inline DataProviderService/DataProviderService.cs]: redundant
