### PR TITLE
Prevent IO exceptions

### LINKED ISSUE #1780: Language setting not persistent
Hello,

I'm french but I play ED in english. I use VoiceAttack with EDDI as plugin. I can set the language to english and it works for a while. But that setting randomly falls back to french. 
It does not happen everytime.

When it happens, I need to open the EDDI standalone and change the language back to english. The combo is blank at that time (cf screenshot). Like it's unable to load the config file and falls back to default.
language settings blank

I used VA/EDDI a year ago with Windows 7 and all was fine. I then stopped playing for a few month.
I now use Windows 10.

## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
Set language in EDDI standalone. Use in voice attack.
On a subsequent session, the language setting in EDDI is blank.
It's random.
I could reproduce today stopping/starting voice attack several times. After the 3rd or 4th, it happened.

## Expected
Language setting kept

## Observed
Language setting randomly blank in EDDI

## Investigation
Tried running both EDDI and VA as admin. Nothing changed.

### PR DESCRIPTION
**Pull request by Tkael**
This PR is designed to prevent issues like:
- https://rollbar.com/EDCD/EDDI/items/17558/
- https://rollbar.com/EDCD/EDDI/items/16979/
- https://rollbar.com/EDCD/EDDI/items/17609/
- https://rollbar.com/EDCD/EDDI/items/17607/
- https://rollbar.com/EDCD/EDDI/items/17583/

It moves file locking from each individual config file into the `Files` class and if an IO exception occurs it waits and retries several times before completely failing.

May resolve #1780.
Replaces #1808.

### CODE REVIEW

**Review by GioVAX — APPROVED** [review]

File: Utilities/Files.cs [hunk 1]
```diff
@@ -18,112 +24,157 @@ public class Files
         /// <summary>
         /// Read a file, handling exceptions
         /// </summary>
-        /// <param name="name"></param>
+        /// <param name="fileName"></param>
         /// <returns></returns>
```
Comment (richardbuckle) [inline Utilities/Files.cs]: returns the contents of the file

File: Utilities/Files.cs [hunk 2]
```diff
@@ -4,11 +4,17 @@
...
 using System.Text;
 using System.Threading;
+using System.Threading.Tasks;
 
 namespace Utilities
 {
     public class Files
     {
+        private const int readAttempts = 10;
+        private const int readIODelayMs = 25;
```
Comment (richardbuckle) [inline Utilities/Files.cs]: `Ms` is technically "megaseconds" in the SI system, because the short names are case-sensitive. Recommend `readIODelayMilliSecs` and similarly for write.

File: Utilities/Files.cs [hunk 3]
```diff
@@ -18,112 +24,157 @@ public class Files
...
                 {
-                    result = File.ReadAllText(name, Encoding.UTF8);
+                    attempts--;
+                    Thread.Sleep(readIODelayMs);
                 }
-                catch (ArgumentException ex)
+                if (attempts == 0)
                 {
-                    Logging.Error("Failed to read from " + name, ex);
+                    throw new IOException("IO read failed for " + fileName + ", too many attempts.");
```
Comment (richardbuckle) [inline Utilities/Files.cs]: I'm a big fan of `$"blah {variable} blah" for readability.

File: Utilities/LockManager.cs [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+namespace Utilities
+{
+
+    // Code from https://www.codeproject.com/Tips/1190802/File-Locking-in-a-Multi-Threaded-Environment
+    // The code maintains a concurrent dictionary of lock objects and keeps track of how many calls are in the queue for
+    // accessing each filename. If the count goes down to 0, the key is removed from the dictionary as a cleanup mechanism.
+    public class LockManager
+    {
+        private static readonly ConcurrentDictionary<string, lobj> _locks =
+                new ConcurrentDictionary<string, lobj>();
```
Comment (richardbuckle) [inline Utilities/LockManager.cs]: Move to one line I think.

**Review by richardbuckle — CHANGES_REQUESTED** [review]
This is good. I can do the fixes myself, no problem.

**Review by richardbuckle — APPROVED** [review]
