### PR TITLE
Fix MaterialDetails() crashing when material is not set

### LINKED ISSUE #1677: Material scripts crash when activated by the test button
## EDDI version in which issue is found
v3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Without Elite loaded, click the Test button for:
Material discard report
Material inventory report
Material location report
Material required report

## Expected
The scripts report what can be discarded or are required, etc., or a test string variation of them.

## Observed
EDDI will crash to desktop.

## Investigation
I was going through the personality with Notepad, looking for scripts with plural IF statements, when I noticed that there appeared to be duplicated (or almost identical) script names.  I went to see if they reported the same thing, so I clicked the test buttons, and that made EDDI CTD.  After the first crash, I tried the other materials reports to see if any others did the same.

As for the duplication, I thought 'Material discard report' and 'Materials discard report' were the same thing (likewise for the '...required...' reports), but then realised one is for a single material, and the other is for all materials.  It was just the very similar names that confused me.

Here's my log for one instance of trying 'Material discard report'.  I loaded EDDI with the default personality, enabled verbose logging, and then clicked the test button.
[eddi.log](https://github.com/EDCD/EDDI/files/4050962/eddi.log)

Let me know if you need anything else.

### PR DESCRIPTION
**Pull request by Tkael**
Resolves #1677.

### CODE REVIEW

File: SpeechResponder/ScriptResolver.cs [hunk 1]
```diff
@@ -917,7 +917,7 @@ private BuiltinStore buildStore(Dictionary<string, Cottle.Value> vars)
                         result.bodyshortname = body.shortname;
                     }
                 }
-                return new ReflectionValue(result);
+                return result == null ? new ReflectionValue(new object()) : new ReflectionValue(result);
```
Comment (richardbuckle) [inline SpeechResponder/ScriptResolver.cs]: How about 
```cs
return new ReflectionValue(result ?? new object());
```
Feels more idiomatic.

Comment (Tkael) [reply SpeechResponder/ScriptResolver.cs]: Done, though I'm not sure you noticed the other methods using the same construction. ;-)
