### PR TITLE
Fix crashing in AX conflict zones

### LINKED ISSUE #1419: some weird crashing going on in ax conflict zones
## EDDI version in which issue is found
3.4.2 b1

## VoiceAttack version in which issue is found (as applicable)
v1.7.7

## Steps to reproduce
1. when in ax conflict zones 
2. not sure if its linked to caustic damage

## Expected
no to crash

## Observed
it crashed

## Investigation
2019-07-27T07:33:11 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI heat warning)) 
2019-07-27T07:33:12 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID dee22dfe-9ded-47bc-859b-645029f82f5e:System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at EddiSpeechService.SpeechQueue.filterSpeechQueue(String type, ConcurrentQueue`1& speechQueue, EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.DequeueSpeechOfType(String type)
   at EddiSpeechService.SpeechQueue.dequeueStaleSpeech(EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.Enqueue(EddiSpeech speech)
   at EddiSpeechService.SpeechService.<>c__DisplayClass33_0.<Say>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 
2019-07-27T07:33:12 [Info] EDDI:Stop EDDI 3.4.2-b1 stopped 

here is another example related to ax conflict zones 

((EDDI hull damaged)) 
2019-07-27T07:28:07 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID dee22dfe-9ded-47bc-859b-645029f82f5e:System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at EddiSpeechService.SpeechQueue.filterSpeechQueue(String type, ConcurrentQueue`1& speechQueue, EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.DequeueSpeechOfType(String type)
   at EddiSpeechService.SpeechQueue.dequeueStaleSpeech(EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.Enqueue(EddiSpeech speech)
   at EddiSpeechService.SpeechService.<>c__DisplayClass33_0.<Say>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 
2019-07-27T07:28:07 [Info] EDDI:Stop EDDI 3.4.2-b1 stopped

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1419.

### CODE REVIEW

File: Tests/SpeechUnitTests.cs [hunk 1]
```diff
@@ -410,5 +411,32 @@ public void TestTranslationVesper()
...
+                // Only the speech of type "Hull damaged" should be removed, null types and other types should remain in place.
+                privateObject.Invoke("DequeueSpeechOfType", new object[] { "Hull damaged" });
+                Assert.AreEqual(2, priorityQueues.SelectMany(q => q).Count());
+                // Verify that the order of remaining speech of the same priority is unchanged.
+                Assert.AreEqual("Test speech 1", priorityQueues[3].First().message);
+                Assert.AreEqual("Test speech 3", priorityQueues[3].Last().message);
+            }
+            catch (System.Exception)
+            {
+                Assert.Fail();
```
Comment (richardbuckle) [inline Tests/SpeechUnitTests.cs]: I expect this catch is so you can clean up below, but just for info it's OK to let an exception leave a test method because the framework will catch it and fail the test for you, with output that includes the exception description.
