### PR TITLE
Spacialise(): Improve handling of complex strings

### LINKED ISSUE #1657: Spacialise() doing something weird with a string for BodyDetails().
## EDDI version in which issue is found
v3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A
## Steps to reproduce
Use Spacialise() on a string and then use that string for BodyDetails().

## Expected
BodyDetails().bodyname to speak the correct body name.

## Observed
Nothing is spoken.

## Investigation
While working on my profile, I just tested out my VA command for more info on a body.  This supplies a body name to EDDI, and EDDI processes that to get a Body Report on the requested body.  I was having trouble with EDDI saying it didn't know what body I was talking about, however, this was working in the past, and I've made no changes to it recently.

I tracked the problem down to a line in my 'Body Info Request' script where the string passed from VA is put through Spacialise().  If I remove this one command, it all works again.  However, I do need the string to be spaced out sometimes, so Spacialise() is important.

So, I've done some further testing.....

Using the following code to test:

```
{set body to "4"}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
Name: {BodyDetails(body_id, system).bodyname}.
```

Any system and body will do, these are just the ones I'm near at the moment.
This results in "Name: Eol Prou KW-L c8-75 4."

Now, if I add the following line:
`{set body to Spacialise(body)}`

Like this:

```
{set body to "4"}
{set body to Spacialise(body)}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
Name: {BodyDetails(body_id, system).bodyname}.
```

This results in "Name: ." and nothing else being spoken.  Spacialise seems to do 'something' to the "4" that makes BodyDetails() not recognise it.

Taking this a step further, I've changed the body to be "4 b".  Without Spacialise(), BodyDetails() works as expected again, saying "Eol Prou KW-L c8-75 4 b".

However, and this is where it gets weird, adding back the Spacialise() results in nothing from BodyDetails(), but if I add a `{body_id}` line, this results in "Eol Prou KW-L c8-75 4spaceb".  The space is litterally spoken as "space", even though the log output shows "...4 b"

This is the code in full:

```
{set body to "4 b"}
{set body to Spacialise(body)}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
{body_id}.
Name: {BodyDetails(body_id, system).bodyname}.
```

Whatever Spacialise() is doing to the string, it's stopping BodyDetails() from working.  Whatever it's doing, it's also affecting a single character string.  And why is the space being voiced as "space"?   Is there anything that can be done to correct this?

Hope you can help.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1657. Improves handling of complex strings with the `Spacialise()` function (and wherever else our `sayAsLettersOrNumbers` method is applied). Prevents "space" and other whitespace characters from being vocalized.

### CODE REVIEW

File: SpeechService/Translations.cs [hunk 1]
```diff
@@ -648,14 +648,24 @@ public static string ICAO(string callsign, bool passDash = false)
 
         public static string sayAsLettersOrNumbers(string part)
         {
-            if (int.TryParse(part, out _))
+            string result = null;
```
Comment (richardbuckle) [inline SpeechService/Translations.cs]: I'll change this to use a StringBuilder for efficiency.
