### PR TITLE
Make hull and module value optional to event

### LINKED ISSUE #751: Exception while swapping modules - hull and module values not always included in Loadout
## EDDI version in which issue found
3.0.1-rc4

## Steps to reproduce
Swap modules after load. 

## Expected
Hull and module values are written and no exceptions are thrown.

## Observed
Hull and module values are not included in Loadout event, exception is thrown. 

Exception:
```
2018-07-22T23:46:37 [Warning] JournalMonitor:ParseJournalEntry Failed to parse line: System.ArgumentException: Unparseable value for HullValue
   at Utilities.JsonParsing.getLong(String key, Object val) in EDDI\Utilities\JsonParsing.cs:line 117
   at Utilities.JsonParsing.getLong(IDictionary`2 data, String key) in EDDI\Utilities\JsonParsing.cs:line 108
   at EddiJournalMonitor.JournalMonitor.ParseJournalEntry(String line) in EDDI\JournalMonitor\JournalMonitor.cs:line 400 
2018-07-22T23:46:37 [Error] JournalMonitor:ParseJournalEntry Exception whilst parsing journal line System.ArgumentException: Unparseable value for HullValue
   at Utilities.JsonParsing.getLong(String key, Object val) in EDDI\Utilities\JsonParsing.cs:line 117
   at Utilities.JsonParsing.getLong(IDictionary`2 data, String key) in EDDI\Utilities\JsonParsing.cs:line 108
   at EddiJournalMonitor.JournalMonitor.ParseJournalEntry(String line) in EDDI\JournalMonitor\JournalMonitor.cs:line 400
```

## Investigation
Confirmed by journal documentation:
```
•	HullValue – may not always be present
•	ModulesValue – may not always be present
```

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #751. Ship value will only be updated if present.

### CODE REVIEW

File: ShipMonitor/ShipLoadoutEvent.cs [hunk 1]
```diff
@@ -31,15 +31,15 @@ static ShipLoadoutEvent()
         public string ship { get; private set; }
         public string shipname { get; private set; }
         public string shipident { get; private set; }
-        public long value => hullvalue + modulesvalue;
-        public long hullvalue { get; private set; }
-        public long modulesvalue { get; private set; }
+        public long? value => hullvalue + modulesvalue ?? null;
```
Comment (richardbuckle) [inline ShipMonitor/ShipLoadoutEvent.cs]: We don't need the `?? null` because of a C# feature called "lifted operators". 
https://stackoverflow.com/questions/3370110/what-are-lifted-operators
