### PR TITLE
Fix `Material threshold` event not firing when we meet but do not exceed our maximum.

### LINKED ISSUE #2085: OBOE in `Material Threshold` event prevents it from firing for `Maximum` level
## What's Wrong (please be as specific as possible)

The [Material threshold](https://github.com/EDCD/EDDI/wiki/Material-threshold-event) event does not fire when you reach the maximum stock for a material.

It works if you lower the maximum by 1, e.g. 150→149 for a grade 4 raw material. The check is `> max` instead of `>= max`.

### Expected

When you fill up on a material, a `Material threshold` event fires.

### Observed

When you fill up on a material, no `Material threshold` event fires.

### Steps to reproduce

1. Leave the default maximum value for a material.
2. Reach the maximum value.
3. No event fires.
4. Lower the maximum value by 1.
5. Reach the (correct) maximum value, aka surpass the new, lowered maximum.
6. An event fires.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 3.7.2
  * VoiceAttack Version: 1.8.7.9 beta

### Investigation Notes

After bringing it up on Discord @Tkael had a look at the code and found the suspected cause. I went and tested it in game.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #2085.

### CODE REVIEW

File: MaterialMonitor/MaterialMonitor.cs [hunk 1]
```diff
@@ -283,7 +283,7 @@ private void incMaterial(string edname, int amount, bool fromLogLoad = false)
 
                 if (ma.maximum.HasValue)
                 {
-                    if (previous <= ma.maximum && ma.amount > ma.maximum)
+                    if (previous <= ma.maximum && ma.amount >= ma.maximum)
```
Comment (richardbuckle) [inline MaterialMonitor/MaterialMonitor.cs]: I generally find it clearer to write everything with all the inequalities facing the same way.
Shouldn't this be `previous < ma.maximum && ma.maximum <= ma.amount`?
Some unit tests here would clarify things.

**Review by richardbuckle — CHANGES_REQUESTED** [review]

File: MaterialMonitor/MaterialMonitor.cs (hunk 1 above)
Comment (Tkael) [reply MaterialMonitor/MaterialMonitor.cs]: Fair enough. Operators sorted and unit test added.
