### PR TITLE
Hotfix/1685 validate personality names and json

### LINKED ISSUE #1685: New personality can crash if malformed file exists
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Create an empty file called "bad.json" in `%APPDATA%\EDDI\personalities`.
2. Launch EDDI and attempt to duplicate the default personality with a name of "bad"

## Expected
EDDI behaves gracefully, e.g. warns you that the name is taken.

## Observed
Crash to desktop from uncaught exception.

## Investigation
Upon investigation, supplying an existing name for a well-formed JSON is not handled as I would expect: it is overwritten without warning.

### PR DESCRIPTION
**Pull request by richardbuckle**
Fixes #1685.
Supersedes #1686.

Implements validation against runtime criteria by implementing `IDataErrorInfo`.

Implements customisation of validation error display via a `Style` resource.

Implements a way to handle OK button enabling based upon validation.

### CODE REVIEW

File: SpeechResponder/Personality.cs [hunk 1]
```diff
@@ -123,7 +123,16 @@ public static Personality FromFile(string filename = null, bool isDefault = fals
...
+                    // malformed JSON for some reason: rename so that the user can examine and fix it.
+                    string newFileName = filename + ".malformed";
+                    if (File.Exists(newFileName))
+                    {
+                        // no point keeping a history: only the latest is likely to be useful. Pro users will be using version control anyway.
+                        File.Delete(newFileName);
+                    }
+                    File.Move(filename, newFileName);
+
+                    Logging.Error($"Could not parse \"{filename}\": moved to \"{newFileName}\". Error was \"{e.Message}\"");
```
Comment (Tkael) [inline SpeechResponder/Personality.cs:135]: This may be worthy of an audible alert or perhaps a message box to alert the user that the personality has been pruned. Thoughts?

File: SpeechResponder/CopyPersonalityWindow.xaml.cs [hunk 2]
```diff
@@ -1,52 +1,122 @@
...
+            Close();
+        }
+
+#region DataErrorInfo
+        // C#'s lack of string-based enums is annoying here. We have to resort to string literals, which are vulnerable to typos.
+        public string Error
+        {
+            get
+            {
+                string result = this["PersonalityName"];
```
Comment (Tkael) [inline SpeechResponder/CopyPersonalityWindow.xaml.cs:81]: Might use `nameof(PersonalityName)` rather than "PersonalityName" to increase resiliency in case variables are later renamed.

File: SpeechResponder/CopyPersonalityWindow.xaml.cs [hunk 3]
```diff
@@ -1,52 +1,122 @@
...
+            }
+        }
+
+        public string this[string fieldName]
+        {
+            get
+            {
+                switch (fieldName)
+                {
+                    case "PersonalityName":
```
Comment (Tkael) [inline SpeechResponder/CopyPersonalityWindow.xaml.cs:94]: As above, might use `nameof(PersonalityName)` rather than "PersonalityName".

File: SpeechResponder/CopyPersonalityWindow.xaml.cs (hunk 2 above)
Comment (richardbuckle) [reply SpeechResponder/CopyPersonalityWindow.xaml.cs:81]: Good idea, thanks.

File: SpeechResponder/CopyPersonalityWindow.xaml.cs (hunk 3 above)
Comment (richardbuckle) [reply SpeechResponder/CopyPersonalityWindow.xaml.cs:94]: ditto

File: SpeechResponder/Personality.cs (hunk 1 above)
Comment (richardbuckle) [reply SpeechResponder/Personality.cs:135]: As discussed in Discord, it's not an error that can arise in normal usage, only when tinkering with the JSON, in which case the user will see the file getting moved, so I think logging at error level is sufficient.
