### PR TITLE
Prevent Status.hardpoints_deployed being set to true in supercruise

### LINKED ISSUE #772: In VA, {BOOL:Status hardpoints deployed} not always correct
## EDDI version in which issue found
3.0.1-rc6, 3.0.1 Release

## Steps to reproduce
Inconsistent.  I can detect when it's going to happen, but I can't determine what is flipping the state variable.  Common precursors are:
1. Using the D-Scanner in supercruise
2. Being interdicted and killing the opponent, then resuming supercruise after stowing hardpoints.

## Expected
Nothing out of the ordinary.

## Observed
Immediately after exiting supercruise at about 9km from the station, my hardpoints deploy.

## Investigation
I've set up an event in Voice Attack to handle the ((EDDI station no fire zone entered)) and then test the value of {BOOL:Status hardpoints deployed} to automatically stow hardpoints.
```
Begin Boolean Compare : [Status hardpoints deployed] Equals True
    Press variable key(s) [edDeployHardpointToggle] and hold for 0.2 seconds and release
    Set Text [Script] to '[we have;][entered;crossed over;crossed into;reached] the no fire zone. [retracting;powering down;disarming;stowing;] [weapons;hard points]'
    Execute external plugin, 'EDDI 3.0.1-rc6' and wait for return
End Condition
```
I've also added a test in my 'Disengage' event to write the status of the {BOOL:Status hardpoints deployed} variable to the VA log window.

Sometimes, rarely, but at least once in a two hour play session, {BOOL:Status hardpoints deployed} is set to TRUE at the time of telling VA to 'Disengage'.  This is impossible as the ship is in Supercruise and usually has been for several moments -- however long it takes to fly 900ls, at least.  Upon exiting supercruise, the ((EDDI station no fire zone entered)) event triggers and, following the value of the deployed state, my VA profile attempts to stow the weapons -- which is a toggle, so they actually deploy within the no-fire zone.

*NOTE* I have not checked to see if {BOOL:EDDI station no fire zone entered weaponsdeployed} is properly set.  I will add some logic to report on that.

### PR DESCRIPTION
**Pull request by Tkael**
FDev sets Status.hardpoints_deployed to true when you use the discovery scanner in supercruise. This has undesirable consequences, so we need to keep Status.hardpoints_deployed false while we are in supercruise.

Fixes #772

### CODE REVIEW

File: DataDefinitions/Status.cs [hunk 1]
```diff
@@ -66,14 +66,17 @@ public enum Flags
...
         public bool flight_assist_off => (flags & Flags.FlightAssistOff) != 0;
         public bool supercruise => (flags & Flags.Supercruise) != 0;
         public bool shields_up => (flags & Flags.ShieldsUp) != 0;
         public bool landing_gear_down => (flags & Flags.LandingGearDown) != 0;
         public bool landed => (flags & Flags.Landed) != 0;
         public bool docked => (flags & Flags.Docked) != 0;
 
+        // FDev changes hardpoints status when the discovery scanner is used in supercruise. 
+        // We want to keep hardpoints_deployed false if we are in supercruise.
+        public bool hardpoints_deployed => ((flags & Flags.HardpointsDeployed) != 0) & !((flags & Flags.Supercruise) != 0);
```
Comment (richardbuckle) [inline DataDefinitions/Status.cs]: BZZT. You need a logical and `&&` there.
