### PR TITLE
Calculate cargo price using a weighted average of acquisition prices

### LINKED ISSUE #1978: Inaccurate cargo price data
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Purchase commodities at station A
2. Dock at station B
3. Manually trigger the `Commodity sales check` script
4. Sell the commodities to trigger the `Commodity sold` script

## Expected
Expected profit should equal actual profit.

## Observed
You can sell your Food Cartridges for a profit of 531900 credits.
You have just sold 788 tonnes of Food Cartridges at 900 credits per tonne for a total of over 709 thousand credits with a profit of over 663 thousand credits.

## Investigation
Applicable events:
```json
{ "timestamp":"2020-10-24T11:09:40Z", "event":"MarketBuy", "MarketID":3228528384, "Type":"foodcartridges", "Type_Localised":"Food Cartridges", "Count":788, "BuyPrice":58, "TotalCost":45704 }
{ "timestamp":"2020-10-24T11:09:43Z", "event":"Cargo", "Vessel":"Ship", "Count":788 }
{ "timestamp":"2020-10-24T11:30:03Z", "event":"MarketSell", "MarketID":3228512000, "Type":"foodcartridges", "Type_Localised":"Food Cartridges", "Count":788, "SellPrice":900, "TotalSale":709200, "AvgPricePaid":58 }
{ "timestamp":"2020-10-24T11:30:06Z", "event":"Cargo", "Vessel":"Ship", "Count":0 }
```

The average market price, per market.json, is 225 credits per ton.
531900 credits: as reported from inventory tracked by the cargo monitor and using average price data, ((900 - 225) * 788).
663496 credits: as reported from the `Commodity sold` (MarketSell) event and using event data, ((900 - 58) * 788).

While the `cargo` object contains a `price` property for the `Commodity sales check` script, that value is not set during the `Commodity purchased` event and consequently does not accurately reflect the actual price paid. The `Cargo` .ctor defaults to using the galaxy average price since no pricing data is provided when the object is created or updated.

Proposal: Re-calculate pricing data when new cargo is acquired using weighted average pricing.

### PR DESCRIPTION
**Pull request by Tkael**
Fixes #1978.
Revises the cargo monitor to calculate a weighted average of the commander's acquisition price for each cargo item (rather than the galactic average price).
Fixes inaccurate projected profits for the `Commodity sales check` script.

### CODE REVIEW

File: CargoMonitor/CargoMonitor.cs [hunk 1]
```diff
@@ -294,25 +300,24 @@ private bool _handleCommodityCollectedEvent(CommodityCollectedEvent @event)
             Cargo cargo = GetCargoWithEDName(@event.commodityDefinition?.edname);
             if (cargo != null)
             {
+                Haulage haulage = cargo.haulageData.FirstOrDefault(h => h.missionid == @event.missionid);
```
Comment (GioVAX) [inline CargoMonitor/CargoMonitor.cs:314]: Can this be 'SingleOrDefault'?
Or can the collection contain multiple items with the same 'missionId'?

File: CargoMonitor/CargoMonitor.cs [hunk 2]
```diff
@@ -493,28 +499,32 @@ private void _handleCargoDepotEvent(CargoDepotEvent @event)
                         {
                             // Cargo instantiated by either 'Mission accepted' event or previous 'WingUpdate' update
                             haulage = cargo.haulageData.FirstOrDefault(ha => ha.missionid == @event.missionid);
```
Comment (GioVAX) [inline CargoMonitor/CargoMonitor.cs:512]: As above: 'SignleOrDefault'?

File: CargoMonitor/CargoMonitor.cs [hunk 3]
```diff
@@ -404,21 +409,22 @@ private void handleCommodityPurchasedEvent(CommodityPurchasedEvent @event)
 
         private bool _handleCommodityPurchasedEvent(CommodityPurchasedEvent @event)
         {
-            bool update = false;
-            Cargo cargo = GetCargoWithEDName(@event.commodityDefinition?.edname);
-            if (cargo != null)
+            Cargo cargo = GetCargoWithEDName(@event.commodityDefinition?.edname) ?? new Cargo(@event.commodityDefinition?.edname);
```
Comment (GioVAX) [inline CargoMonitor/CargoMonitor.cs:423]: Can we move 'new Cargo(...)' inside 'GetCargoWithEDName'?
I see the same pattern below and it could remove some duplication, but I do not know if this is used in different ways in other parts of the code.

File: DataDefinitions/Cargo.cs [hunk 4]
```diff
@@ -6,35 +6,34 @@
...
         public string invariantName => commodityDef?.invariantName ?? "";
-        [JsonIgnore]
+
         public string localizedName => commodityDef?.localizedName ?? "";
-        [JsonIgnore, Obsolete("Please use localizedName or invariantName")]
+        
+        [Obsolete("Please use localizedName or invariantName")]
         public string name => localizedName;
 
+        [JsonProperty("edname")]
```
Comment (GioVAX) [inline DataDefinitions/Cargo.cs:25]: Nice  =)

**Review by GioVAX — COMMENTED** [review]
Added some nits

File: CargoMonitor/CargoMonitor.cs (hunk 1 above)
Comment (Tkael) [reply CargoMonitor/CargoMonitor.cs:314]: The general pattern Hooda appeared to follow was to try to look up haulage, then only add it if it was missing. Consequently, I don't think it's intended to contain multiple items with the same missionId but you're right that it isn't designed to prevent it. I have tried to write my changes to preclude that possibility, but since there is no duplicate protection built in I think that swapping to use 'SingleOrDefault' does create additional risk.

The same is true for cargo in the inventory collection.

We could consider creating a separate ticket to transition from lists to dictionaries for both the cargo in inventory and for haulage (using commodity `edname` as a unique key for cargo and haulage `missionid` as a unique key for haulage) but doing so could have implications for other dependent projects and is would have a wider impact than I intended for this first pass.

File: CargoMonitor/CargoMonitor.cs (hunk 2 above)
Comment (Tkael) [reply CargoMonitor/CargoMonitor.cs:512]: As above

File: CargoMonitor/CargoMonitor.cs (hunk 3 above)
Comment (Tkael) [reply CargoMonitor/CargoMonitor.cs:423]: I count 6 references with methods which are conditional on whether the return value is null:
- _handleCommodityCollectedEvent
- _handleCommodityEjectedEvent
- _handleCommodityRefinedEvent
- handleCommoditySoldEvent
- _handleMissionCompletedEvent
- _handleEngineerContributedEvent

I also count 5 references where we instantiate `new Cargo` if the return is null. We could create a new method `GetOrCreateCargoWithEDName` to help distinguish this case if we think that doing so adds sufficient value.

File: CargoMonitor/CargoMonitor.cs (hunk 1 above)
Comment (richardbuckle) [reply CargoMonitor/CargoMonitor.cs:314]: I would prefer to leave it as is for now.

File: CargoMonitor/CargoMonitor.cs (hunk 3 above)
Comment (richardbuckle) [reply CargoMonitor/CargoMonitor.cs:423]: Well, in general any "get by name" lookup *should* return null if the item is not there, and it is the caller's responsibility to decide what to do about it. If we did make this change, we would definitely have to call it `GetOrCreateCargoWithEDName` instead, otherwise the function name is lying to us.

But on reflection I think I rather prefer having the error handling out there and in our faces in this case.

File: DataDefinitions/Cargo.cs [hunk 5]
```diff
@@ -142,8 +143,7 @@ private void OnDeserialized(StreamingContext context)
             if (commodityDef == null)
             {
                 // legacy JSON with no edname in the top level
-                string edname = (string)_additionalJsonData["commodity"]["edname"];
-                commodityDef = CommodityDefinition.FromEDName(edname);
```
Comment (richardbuckle) [inline DataDefinitions/Cargo.cs:146]: I might be missing something here. Don't we need this to load the CommodityDefinition from JSON correctly?

File: DataDefinitions/Cargo.cs [hunk 6]
```diff
@@ -154,28 +154,115 @@ private void OnDeserialized(StreamingContext context)
...
+                need = haulageData.Sum(h => h.need);
+            }
+        }
+
+        public void CalculateWeightedPrice(int thisPrice, int amount)
+        {
+            if (amount == 0) { return; }
+            var weightedValueSum = (weightedAvgPrice * total) + (thisPrice * amount);
+            var weightedQtySum = total + amount;
+            weightedAvgPrice = weightedValueSum / weightedQtySum;
```
Comment (richardbuckle) [inline DataDefinitions/Cargo.cs]: Do we need to guard against divide by zero here, such as when we sell everything?

File: DataDefinitions/Cargo.cs [hunk 7]
```diff
@@ -154,28 +154,115 @@ private void OnDeserialized(StreamingContext context)
...
+            NotifyPropertyChanged("price");
+        }
+
+        /// <summary> </summary>
+        /// <param name="cargoType">The type of cargo to add</param>
+        /// <param name="amount">The amount of cargo to add</param>
+        /// <param name="cargoHaulageData">Add or update haulage instance</param>
+        /// <param name="_price">The acquisition price per unit (if not zero)</param>
+        public void AddDetailedQty(CargoType cargoType, int amount, Haulage cargoHaulageData = null, int _price = 0)
```
Comment (richardbuckle) [inline DataDefinitions/Cargo.cs]: A couple of things.

1. Leading underscores are a convention for private instance variables and methods. It's not conventional to use them to disambiguate a parameter from an existing instance variable and such a clash usually indicates that a better name is needed for the parameter. Suggest `acquistionPrice` here.

2. I'm not sure that defaulting `acquistionPrice` to zero is a good idea. I would rather make callers think about it and pass zero explicitly if appropriate. This would of course mean making it the 3rd param, but I am OK with that.

File: DataDefinitions/Cargo.cs [hunk 8]
```diff
@@ -154,28 +154,115 @@ private void OnDeserialized(StreamingContext context)
...
         {
-            if (this != null && this.haulageData != null && this.haulageData.Any())
+            if (haulageData != null && haulageData.Any())
+            {
+                need = haulageData.Sum(h => h.need);
+            }
+        }
+
+        public void CalculateWeightedPrice(int thisPrice, int amount)
+        {
```
Comment (richardbuckle) [inline DataDefinitions/Cargo.cs:178]: "Calculate" implies no change to the object.
Let's rename this `UpdateWeightedPrice(int newPrice, int newAmount)`.

File: DataDefinitions/Cargo.cs [hunk 9]
```diff
@@ -154,28 +154,115 @@ private void OnDeserialized(StreamingContext context)
...
+                    {
+                        haulage += amount;
+                        if (cargoHaulageData != null) 
+                        {
+                            for (int i = 0; i < haulageData.Count; i++)
+                            {
+                                if (haulageData[i].missionid == cargoHaulageData.missionid)
+                                {
+                                    haulageData[i] = cargoHaulageData;
+                                    return;
```
Comment (richardbuckle) [inline DataDefinitions/Cargo.cs]: A `return` this deep is always a bit of a loaded gun should the code be blindly moved into another context.

I would instead of the manual `for` loop use `haulageData.FindIndex()` with a predicate and update if found or Add() if not.

File: DataDefinitions/Cargo.cs [hunk 10]
```diff
@@ -154,28 +154,115 @@ private void OnDeserialized(StreamingContext context)
...
+        /// <param name="cargoType">The type of cargo to remove</param>
+        /// <param name="amount">The amount of cargo to remove</param>
+        /// <param name="cargoHaulageData">Remove haulage instance</param>
+        public void RemoveDetailedQty(CargoType cargoType, int amount, Haulage cargoHaulageData = null)
+        {
+            switch (cargoType)
             {
-                this.need = this.haulageData.Sum(h => h.need);
+                case CargoType.haulage:
+                    {
```
Comment (richardbuckle) [inline DataDefinitions/Cargo.cs:247]: Such braces are only required if the block is introducing new local vars.

File: CargoMonitor/CargoMonitor.cs [hunk 11]
```diff
@@ -953,15 +1000,19 @@ private void readInventory(CargoMonitorConfiguration configuration = null)
...
-
+            if (cargo == null) { return; }
             lock (inventoryLock)
             {
+                for (int i = 0; i < inventory.Count; i++)
+                {
+                    if (string.Equals(inventory[i].edname, cargo.edname, StringComparison.InvariantCultureIgnoreCase))
+                    {
+                        inventory[i] = cargo;
+                        return;
```
Comment (richardbuckle) [inline CargoMonitor/CargoMonitor.cs]: A `return` this deep is always a bit of a loaded gun should the code be blindly moved into another context.

I would instead of the manual `for` loop use `inventory.FindIndex()` with a predicate and update if found or Add() if not.

**Review by richardbuckle — CHANGES_REQUESTED** [review]

File: DataDefinitions/Cargo.cs (hunk 5 above)
Comment (Tkael) [reply DataDefinitions/Cargo.cs:146]: Nope, it's redundant. What you're missing is this (from the same file):
```cs
        public string edname
        {
            get => commodityDef.edname;
            set
            {
                CommodityDefinition cDef = CommodityDefinition.FromEDName(value);
                this.commodityDef = cDef;
            }
        }
```

File: DataDefinitions/Cargo.cs (hunk 6 above)
Comment (Tkael) [reply DataDefinitions/Cargo.cs]: Good call. Anytime we do division, we need to watch out for that.

File: DataDefinitions/Cargo.cs (hunk 8 above)
Comment (Tkael) [reply DataDefinitions/Cargo.cs:178]: Agreed.

File: DataDefinitions/Cargo.cs (hunk 7 above)
Comment (Tkael) [reply DataDefinitions/Cargo.cs]: Good calls.

File: DataDefinitions/Cargo.cs (hunk 10 above)
Comment (Tkael) [reply DataDefinitions/Cargo.cs:247]: Fair. I think it's probably a good practice anyways.

**Comment by richardbuckle** [comment]
Created #1997 to encapsulate my desired fixes here.

**Review by richardbuckle — APPROVED** [review]
